### PR TITLE
 Add scheme in parse_list_output method when there is no email address

### PR DESCRIPTION
**Pull request by Alice-Qiu**
### Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by reidmorrison** [comment]
Thank you for the PR. After testing locally I had to change the order of the if statements to still handle addresses with emails. It should work now from master.

**Comment by Alice-Qiu** [comment]
Cool, thanks so much!

**Comment by Alice-Qiu** [comment]
Can you tag a new release for the recent changes? Thanks!

**Comment by reidmorrison** [comment]
Changes are now available in gem: iostreams v1.3.0

**Pull request merged**
